include $(BOARD_DIR)/firmware/firmware.mk

BOARDINC += $(BOARD_DIR)/generated/controllers/generated

# defines SHORT_BOARD_NAME
include $(BOARD_DIR)/meta-info.env

# this would save some flash while being unable to update WBO controller firmware
DDEFS += -DEFI_WIDEBAND_FIRMWARE_UPDATE=FALSE

DDEFS += -DEFI_MAIN_RELAY_CONTROL=FALSE

# MCU defines
DDEFS += -DSTM32F407xx

# reduce memory usage monitoring
DDEFS += -DRAM_UNUSED_SIZE=100

DDEFS += -DSTM32_ADC_USE_ADC3=TRUE
# todo: make knock pin software-selectable?
DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE -DSTM32_ADC_USE_ADC3=TRUE
DDEFS += -DKNOCK_SPECTROGRAM=FALSE

# assign critical LED to a non-existent pin if you do not have it on your board
# good old PD14 is still the default value
DDEFS += -DLED_CRITICAL_ERROR_BRAIN_PIN=Gpio::I15

# --- ACTIVACIÓN DE HARDWARE Y DRIVERS ---
DDEFS += -DSTM32_UART_USE_USART1=TRUE
DDEFS += -DSTM32_UART_USE_USART2=TRUE

# --- CONFIGURACIÓN PUERTO PRIMARIO ---
DDEFS += -DTS_PRIMARY_UxART_PORT=UARTD1
DDEFS += -DTS_PRIMARY_BAUDRATE=115200
DDEFS += -DEFI_CONSOLE_TX_BRAIN_PIN=Gpio::D6
DDEFS += -DEFI_CONSOLE_RX_BRAIN_PIN=Gpio::D5

# --- CONFIGURACIÓN PUERTO SECUNDARIO ---
//DDEFS += -DTS_SERIAL_PORT2=UARTD2
//DDEFS += -DTS_SERIAL_PORT2_BAUDRATE=115200
//DDEFS += -DEFI_CONSOLE_TX_BRAIN_PIN_2=Gpio::D6
//DDEFS += -DEFI_CONSOLE_RX_BRAIN_PIN_2=Gpio::D5

# --- AJUSTES DE EFIFEATURES ---
//DDEFS += -DEFI_TEXT_LOGGING=FALSE
//DDEFS += -DTS_NO_LOGS=TRUE
//DDEFS += -DEFI_CLI_SUPPORT=FALSE

# we do not have much Lua RAM, let's drop some fancy functions
DDEFS += -DWITH_LUA_CONSUMPTION=FALSE
DDEFS += -DWITH_LUA_PID=FALSE
DDEFS += -DWITH_LUA_STOP_ENGINE=FALSE

