include $(BOARD_DIR)/firmware/firmware.mk

BOARDINC += $(BOARD_DIR)/generated/controllers/generated

# defines SHORT_BOARD_NAME
include $(BOARD_DIR)/meta-info.env

# this would save some flash while being unable to update WBO controller firmware
DDEFS += -DEFI_WIDEBAND_FIRMWARE_UPDATE=FALSE

DDEFS += -DEFI_MAIN_RELAY_CONTROL=FALSE

# MCU defines
DDEFS += -DSTM32F407xx

# reduce memory usage monitoring
DDEFS += -DRAM_UNUSED_SIZE=100

DDEFS += -DSTM32_ADC_USE_ADC3=TRUE
# todo: make knock pin software-selectable?
DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE -DSTM32_ADC_USE_ADC3=TRUE
DDEFS += -DKNOCK_SPECTROGRAM=FALSE

# assign critical LED to a non-existent pin if you do not have it on your board
# good old PD14 is still the default value
DDEFS += -DLED_CRITICAL_ERROR_BRAIN_PIN=Gpio::I15

DDEFS += -DHAL_USE_UART=FALSE
DDEFS += -DEFI_USE_UART_DMA=FALSE

# --- CONFIGURACIÓN PUERTO PRIMARIO ---
DDEFS += -DSTM32_SERIAL_USE_USART1=TRUE
DDEFS += -DSTM32_SERIAL_USART1_PRIORITY=6
DDEFS += -DTS_PRIMARY_UxART_PORT=SD1
DDEFS += -DEFI_TS_PRIMARY_IS_SERIAL=TRUE
DDEFS += -DTS_PRIMARY_BAUDRATE=115200
DDEFS += -DEFI_CONSOLE_TX_BRAIN_PIN=Gpio::A10
DDEFS += -DEFI_CONSOLE_RX_BRAIN_PIN=Gpio::A9

# --- CONFIGURACIÓN PUERTO SECUNDARIO ---
DDEFS += -DSTM32_SERIAL_USE_USART2=TRUE
DDEFS += -DSTM32_SERIAL_USART2_PRIORITY=6
DDEFS += -DTS_SECONDARY_UxART_PORT=SD2
DDEFS += -DEFI_TS_SECONDARY_IS_SERIAL=TRUE
DDEFS += -DTS_SECONDARY_BAUDRATE=115200
DDEFS += -DEFI_CONSOLE_TX_BRAIN_PIN_2=Gpio::D6
DDEFS += -DEFI_CONSOLE_RX_BRAIN_PIN_2=Gpio::D5

# we do not have much Lua RAM, let's drop some fancy functions
DDEFS += -DWITH_LUA_CONSUMPTION=FALSE
DDEFS += -DWITH_LUA_PID=FALSE
DDEFS += -DWITH_LUA_STOP_ENGINE=FALSE

# --- DESACTIVACIÓN TOTAL DE PERIFÉRICOS ---
DDEFS += -DHAL_USE_USB=FALSE
DDEFS += -DEFI_USB_SERIAL=FALSE
DDEFS += -DHAL_USE_SPI=FALSE
DDEFS += -DSTM32_SPI_USE_SPI1=FALSE
DDEFS += -DSTM32_SPI_USE_SPI2=FALSE
DDEFS += -DSTM32_SPI_USE_SPI3=FALSE
DDEFS += -DEFI_STORAGE_SD=FALSE
DDEFS += -DEFI_CAN_SUPPORT=FALSE

# --- MAXIMIZAR PRIORIDAD DE COMUNICACIÓN ---
# Bajamos el valor de prioridad (en ChibiOS, menor número = más prioridad)
# Ponemos la prioridad de los puertos serie casi al nivel de los Timers
DDEFS += -DSTM32_SERIAL_USART1_PRIORITY=2
DDEFS += -DSTM32_SERIAL_USART2_PRIORITY=2
DDEFS += -DSTM32_SERIAL_USART3_PRIORITY=2

# --- OPTIMIZACIÓN DE PROTOCOLO BINARIO ---
DDEFS += -DEFI_TEXT_LOGGING=FALSE
DDEFS += -DTS_NO_LOGS=TRUE
DDEFS += -DEFI_ENGINE_SNIFFER=FALSE
DDEFS += -DEFI_TS_SCATTER=FALSE
DDEFS += -DTS_IDLE_TIMEOUT_MS=0
DDEFS += -DTS_BLOCKING_TIMEOUT_MS=0
DDEFS += -DTS_OUTPUT_BUFFER_SIZE=2048

DDEFS += -DEFI_CLI_SUPPORT=FALSE
DDEFS += -DEFI_INTERNAL_FLASH_RECORDER=FALSE
# Forzar al protocolo TS a no dormir NADA entre paquetes
DDEFS += -DTS_SLEEP_MS=0
DDEFS += -DTS_PRIMARY_IDLE_TIMEOUT_MS=0

# Intentar subir la velocidad de respuesta del buffer
DDEFS += -DTS_UART_WRITE_BUFFER_SIZE=1024
